### PR TITLE
Adding tests

### PR DESCRIPTION
**Pull request by melpetera**

### CODE REVIEW

**Comment by melpetera** [comment]
It seems I made something wrong but I can not figure out what exactly.

**Comment by lecorguille** [comment]
Actually, your inputs and outputs are the same because any of your parameters are used.
Which is also a good test :)

**Comment by lecorguille** [comment]
Green Green Green 👍

**Comment by lecorguille** [comment]
Tell me as soon as you push it to the ToolShed

**Comment by lecorguille** [comment]
@melpetera 
I want to update the docker image before our talk on thuesday at GCC.
 - Can I merge on the `master`?
 - Can you push ASAP this new version on the Main ToolShed?

**Comment by melpetera** [comment]
Tested on dev.
I will do the PR for master branch and the TS update.

**Pull request merged**
